apiVersion: 1

datasources:
  - name: REDiTECH 3CX
    uid: reditech-3cx-ds
    type: grafana-postgresql-datasource
    access: proxy
    url: ${GF_DS_REDITECH_HOST}
    database: ${GF_DS_REDITECH_DATABASE}
    user: ${GF_DS_USER}
    jsonData:
      sslmode: ${GF_DS_SSL_MODE}
      postgresVersion: 1600
    secureJsonData:
      password: ${GF_DS_PASSWORD}

  - name: TCC 3CX
    uid: tcc-3cx-ds
    type: grafana-postgresql-datasource
    access: proxy
    url: ${GF_DS_TCC_HOST}
    database: ${GF_DS_TCC_DATABASE}
    user: ${GF_DS_USER}
    jsonData:
      sslmode: ${GF_DS_SSL_MODE}
      postgresVersion: 1600
    secureJsonData:
      password: ${GF_DS_PASSWORD}
