apiVersion: 1

datasources:
  - name: REDiTECH 3CX
    uid: reditech-3cx-ds
    type: grafana-postgresql-datasource
    access: proxy
    url: ${GF_DS_REDITECH_HOST:- db:5432}
    database: ${GF_DS_REDITECH_DATABASE:- reditech3cx_database}
    user: ${GF_DS_REDITECH_USER:- tcx_user}
    jsonData:
      sslmode: ${GF_DS_SSL_MODE:- disable}
      postgresVersion: 1600
    secureJsonData:
      password: ${GF_DS_REDITECH_PASSWORD:- changeme}

  - name: TCC 3CX
    uid: tcc-3cx-ds
    type: grafana-postgresql-datasource
    access: proxy
    url: ${GF_DS_TCC_HOST:- db:5432}
    database: ${GF_DS_TCC_DATABASE:- tcc3cx_database}
    user: ${GF_DS_TCC_USER:- tcc_tcx}
    jsonData:
      sslmode: ${GF_DS_SSL_MODE:- disable}
      postgresVersion: 1600
    secureJsonData:
      password: ${GF_DS_TCC_PASSWORD:- changeme}
